//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobs
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public Nullable<int> Rider_Id { get; set; }
        public Nullable<decimal> Review_Score { get; set; }
        public string Review_Comment { get; set; }
        public Nullable<System.TimeSpan> Completed_At { get; set; }
    }
}
